# Form implementation generated from reading ui file 'load_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Load(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(484, 269)
        self.files_path = QtWidgets.QLineEdit(parent=Dialog)
        self.files_path.setEnabled(False)
        self.files_path.setGeometry(QtCore.QRect(50, 90, 341, 31))
        self.files_path.setReadOnly(True)
        self.files_path.setObjectName("files_path")
        self.cancel_button = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(100, 180, 121, 31))
        self.cancel_button.setObjectName("cancel_button")
        self.files_button = QtWidgets.QToolButton(parent=Dialog)
        self.files_button.setGeometry(QtCore.QRect(400, 100, 25, 19))
        self.files_button.setObjectName("files_button")
        self.load_button = QtWidgets.QPushButton(parent=Dialog)
        self.load_button.setGeometry(QtCore.QRect(250, 180, 121, 31))
        self.load_button.setObjectName("load_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.files_path.setPlaceholderText(_translate("Dialog", "Select Folder or File"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.files_button.setText(_translate("Dialog", "..."))
        self.load_button.setText(_translate("Dialog", "Load"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
