# Form implementation generated from reading ui file 'home_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 616)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(290, 20, 391, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.title.setAutoFillBackground(False)
        self.title.setScaledContents(False)
        self.title.setObjectName("title")
        self.background = QtWidgets.QLabel(parent=self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 921, 591))
        self.background.setText("")
        #self.background.setPixmap(QtGui.QPixmap("images/background.jpg"))
        #self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.make_queries = QtWidgets.QPushButton(parent=self.centralwidget)
        self.make_queries.setGeometry(QtCore.QRect(390, 230, 151, 41))
        self.make_queries.setObjectName("make_queries")
        self.load_data = QtWidgets.QPushButton(parent=self.centralwidget)
        self.load_data.setGeometry(QtCore.QRect(390, 290, 151, 41))
        self.load_data.setObjectName("load_data")
        self.documentation = QtWidgets.QPushButton(parent=self.centralwidget)
        self.documentation.setGeometry(QtCore.QRect(390, 350, 151, 41))
        self.documentation.setObjectName("documentation")
        self.background.raise_()
        self.title.raise_()
        self.make_queries.raise_()
        self.load_data.raise_()
        self.documentation.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Information Retrieval For Documents"))
        self.make_queries.setText(_translate("MainWindow", "Make Queries"))
        self.load_data.setText(_translate("MainWindow", "Load Data"))
        self.documentation.setText(_translate("MainWindow", "Documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
